from tkinter import *


base=Tk()
base.geometry('300x400')
#base.title("Calculator")
#base.configure(bg='light grey')
#amey.place(y=370,x=90)
#bg=Label(base,bg='light grey',width=1200,height=2)
#bg.place(y=0,x=0)

base.title("Calculator")
base.configure(bg='light grey')
bg=Label(base,bg='light grey',width=1200,height=2)
bg.place(y=0,x=0)
typecal=Label(base,text="Standard")
typecal.configure(font=('arial bold',15),bg='light grey')
typecal.place(y=0,x=100)
bgc=Label(base,bg='light yellow',width=1200,height=2)
bgc.place(y=35,x=0)
cal=Entry(base,bg='light yellow',width=50,font=('arial bold',15))
cal.place(y=35,x=0)
cal.insert(0,'0')


def modc():
    a=cal.get()
    if a=='0':
        return
    cal.insert(END,'%')
mod=Button(base,text="%",width=8,height=2,command=modc)
mod.place(y=90,x=10)#by amey 
def seven():
    a=cal.get()
    if a=='0':
       cal.delete(0,END)
    cal.insert(END,'7')

sevenb=Button(base,text="7",width=8,height=2,command=seven)
sevenb.place(y=140,x=10)
def four():
    a=cal.get()
    if a=='0':
        cal.delete(0,END)
    cal.insert(END,'4')
fourb=Button(base,text='4',width=8,height=2,command=four)
fourb.place(y=190,x=10)

def one():
    a=cal.get()
    if a=='0':
        cal.delete(0,END)
    cal.insert(END,'1')
oneb=Button(base,text='1',width=8,height=2,command=one)
oneb.place(y=240,x=10)

def zeros():
    a=cal.get()
    if a=='0':
        cal.delete(0,END)
    cal.insert(END,'00')
zerosb=Button(base,text="00",width=8,height=2,command=zeros)
zerosb.place(y=290,x=10)
def clear():
    cal.delete(0,END)
    cal.insert(0,'0')

ce=Button(base,text='CE',width=8,height=2,command=clear)
ce.place(y=90,x=80)
def eight():
    a=cal.get()
    if a=='0':
        cal.delete(0,END)
    cal.insert(END,'8')
eightb=Button(base,text="8",width=8,height=2,command=eight)
eightb.place(y=140,x=80)

def five():
    a=cal.get()
    if a=='0':
        cal.delete(0,END)
    cal.insert(END,'5')
fiveb=Button(base,text='5',width=8,height=2,command=five)
fiveb.place(y=190,x=80)

def two():
    a=cal.get()
    if a=='0':
        cal.delete(0,END)
    cal.insert(END,'2')
twob=Button(base,text='2',width=8,height=2,command=two)
twob.place(y=240,x=80)

def zero():
    a=cal.get()
    if a=='0':
        cal.delete(0,END)
    cal.insert(END,'0')
zerob=Button(base,text='0',width=8,height=2,command=zero)
zerob.place(y=290,x=80)


c=Button(base,text='C',width=8,height=2,command=clear)
c.place(y=90,x=150)
def nine():
    a=cal.get()
    if a=='0':
        cal.delete(0,END)
    cal.insert(END,'9')
nineb=Button(base,text='9',width=8,height=2,command=nine)
nineb.place(y=140,x=150)
def six():
    a=cal.get()
    if a=='0':
        cal.delete(0,END)
    cal.insert(END,'6')#by amey 
sixb=Button(base,text='6',width=8,height=2,command=six)
sixb.place(y=190,x=150)
def three():
    a=cal.get()
    if a=='0':
        cal.delete(0,END)
    cal.insert(END,'3')
threeb=Button(base,text='3',width=8,height=2,command=three)
threeb.place(y=240,x=150)
def dot():
    a=int(cal.get())
    if a==0:
        cal.insert(END,".0")
        return
    cal.insert(END,".")
dotb=Button(base,text='.',width=8,height=2,command=dot)
dotb.place(y=290,x=150)

def div():
    a=cal.get()
    if a=='0':
        return
    cal.insert(END,"/")
division=Button(base,text='/',width=8,height=2,command=div)
division.place(y=90,x=220)

def mul():
    a=cal.get()
    if a=='0':
        return
    cal.insert(END,'*')
mulb=Button(base,text='x',width=8,height=2,command=mul)
mulb.place(y=140,x=220)#by amey
def sub():
    a=cal.get() 
    if a=='0':
        return
    cal.insert(END,'-')
subb=Button(base,text='-',width=8,height=2,command=sub)
subb.place(y=190,x=220)

def add():
    a=cal.get()
    if a=='0':
        return
    cal.insert(END,'+')
addb=Button(base,text='+',width=8,height=2,command=add)
addb.place(y=240,x=220)
def equal():
    try:
        a=eval(cal.get())
    except:
        a="Syntax Error generated By Amey"
    cal.delete(0,END)
    cal.insert(0,a)
equalb=Button(base,text='=',width=8,height=2,command=equal)
equalb.place(y=290,x=220)


base.mainloop()
